### ISSUE TITLE
"Когда в последний раз заказывали воду?"

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/mona#1]
Mona should be able to say date of last water order.

<img width="560" alt="screen shot 2015-09-17 at 10 21 19 am" src="https://cloud.githubusercontent.com/assets/800337/9927301/36ea3030-5d26-11e5-9471-d024036d0648.png">

**Comment by Nailan** [comment]
@Proghat is it actual?

**Comment by dzhlobo** [comment]
Why not? It’s not a top-priority feature but still may be useful.

**Comment by bronydell** [comment]
See #16

**Comment by AleksSenkou** [comment]
@bronydell as I understand this one can be closed due to #16?

**Comment by AleksSenkou** [comment]
has already been implemented
