### ISSUE TITLE
Communication script on the English day

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/mona#15]
Probably communication.js script is not working corrent on the our English Thursday.

In English day mona:
- should use only English greetings 
- shouldn't say "hello" on Russians greetings from datarockets

<img width="1680" alt="screen shot 2017-09-21 at 10 26 20" src="https://user-images.githubusercontent.com/7738063/30683755-55a4993c-9eb7-11e7-8f9c-0c256c9751f9.png">

**Comment by ezhlobo** [comment]
Sometimes mona says "Good morning in our English day!" on other days

**Comment by bronydell** [comment]
See #16

**Comment by AleksSenkou** [comment]
@bronydell as I understand this one can be closed due to #16?

**Comment by bronydell** [comment]
@AleksSenkou no, bug still exists

**Comment by andrei-sheina** [comment]
@bronydell I guess we should also force mona to use only English phrases (like greetings) during English day

![image](https://user-images.githubusercontent.com/11193254/42623930-cd451118-85cc-11e8-90b7-75edcf1a02fc.png)

**Comment by AleksSenkou** [comment]
Looks like not relevant for now: no English Thursday - no bugs 😄
