### ISSUE TITLE
English day reminder

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/mona#2]
Mona should remind team about English day (everyone speak English this day :)).

Also it could warn about using Russian words during this day.

**Comment by ezhlobo** [comment]
@Proghat Has Mona access to DMs?

Would be good feature to warn about Russian in directly messages also. What about it?

**Comment by dzhlobo** [comment]
No, she doesn't. It's insecure and not private. I think we should do anything with DM.

**Comment by Nailan** [comment]
Implemented
