### ISSUE TITLE
Mona should not take care about messages in the code snippets

### ISSUE THREAD

**Issue by ezhlobo** [datarockets/mona#20]
![screen shot 2018-07-19 at 11 28 02](https://user-images.githubusercontent.com/974552/42930886-ec84d2a0-8b46-11e8-9fdc-af982de7e98b.png)

It looks like if we use something like `Hello` in code snippets Mona reacts on them, but she should not.

**Comment by nikitasakau** [comment]
This feature is already implemented in [PR#45](https://github.com/datarockets/mona/pull/45), but I would like to close this issue after merging to master.

**Comment by lazycoder9** [comment]
Can we close this issue?

**Comment by AleksSenkou** [comment]
@lazycoder9, Nikita @nikitasakov said that he wants to close it after merging to master. Please close if it's merged

**Comment by nikitasakau** [comment]
Yeah, this issue related not only to Botkit Mona, so I think we should close it when it will be in master 🙂
