### ISSUE TITLE
Make Mona only English-spoken?

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/mona#26]
Due to English-spoken teammate, it can make sense to have only English language for messages from Mona

**Comment by DDKatch** [comment]
going to work on that 😉

**Comment by AleksSenkou** [comment]
@DDKatch for resolving the issue by merging PR we need to write something from [the list](https://github.blog/2013-05-14-closing-issues-via-pull-requests/) 😉 

Satisfied
