### ISSUE TITLE
I'd like to get some funny reaction when I accidentally spoke in Russian instead of English

### ISSUE THREAD

**Issue by DDKatch** [datarockets/mona#29]
We've decided to speak in Russian only in several channels: #office and #random (if I am not mistaken). It would be cool to have some sort of funny reaction to Russian speech in other channels.

**Comment by AleksSenkou** [comment]
@DDKatch What if we add another russian-allowed channel in slack, will we need to update the list of channels in the source code?

**Comment by DDKatch** [comment]
We may use some code for checking Russian language:
```
const cyrillicQuery = /[\u0400-\u04FF]+/;
if (query === cyrillicQuery) {
    return response.send("It's, uncool. Speak in English, please :slightly_smiling_face:");
}
```

**Comment by DDKatch** [comment]
> @DDKatch What if we add another russian-allowed channel in slack, will we need to update the list of channels in the source code?

@AleksSenkou we can add a command for that

**Comment by AleksSenkou** [comment]
@DDKatch thoughts about arguing about Russian only in #general channel?

The thing is that we'll probably have other issues with Russian-strict in different places and it may become a pain for us to fix/adjust code.

What we are preventing with such behavior of Mona? Most of the people write on English but sometimes can post Russian by accident, no need to accent that. Thoughts?

**Comment by DDKatch** [comment]
@AleksSenkou 🤔 You're right, people make better jokes than the bots. I mean that it's our responsibility to joke about that 😉

**Comment by DDKatch** [comment]
@AleksSenkou I think we can close this issue, don't you think so?

**Comment by AleksSenkou** [comment]
@AleksSenkou as you wish :)
