### ISSUE TITLE
Mona doesn't mention in answers

### ISSUE THREAD

**Issue by ezhlobo** [datarockets/mona#3]
![screen shot 2015-11-13 at 15 32 24](https://cloud.githubusercontent.com/assets/974552/11146103/5000496a-8a1c-11e5-9764-64c4af346327.png)

You should add `@` before nickname I think.

**Comment by chyrta** [comment]
Nice idea.

**Comment by dzhlobo** [comment]
It's hubot-slack issue. Already resolved: https://github.com/slackhq/hubot-slack/pull/242. Could you please upgrade hubot-slack dependency to latest version?

**Comment by ezhlobo** [comment]
I don't see this problem any more.
