### ISSUE TITLE
When I develop the bot I'd like to cover core features with tests

### ISSUE THREAD

**Issue by DDKatch** [datarockets/mona#31]
**Tension**
I believe that mona is a long term project which may evolve, so It's better to have tests.

**Solution**
Write unit tests for features with https://github.com/gratifyguy/botkit-mock support

**Comment by nikitasakau** [comment]
As I understand we have already added `botkit-mock` to project in our move-to-botkit branch. Also  some examples are already added

**Comment by npupko** [comment]
@nikitasakov I found strange behavior in tests in the process of writing tests for #24.
For example when you try to change this line:
`specs/greeting_spec.js:21`
```js
// from
- }]).then(message => assert(replies.includes(message.text)))
// to 
- }]).then(message => assert(universal_emptiness.includes(microparticles)))
```
nothing will happens and the spec will pass.

The controller code isn't called.

**Comment by nikitasakau** [comment]
@npupko As I wrote earlier I found some strange things too and was working on fixing. Please check the `botkit-fix-greeting` branch. I've updated some packages there. Is what you found corrected there?

**Comment by npupko** [comment]
@nikitasakov Yep, it works well.

**Comment by nikitasakau** [comment]
I think we can close this issue because infrastructure for tests are implemented. Let me know if you don't agree

**Comment by npupko** [comment]
@nikitasakov +1 
We have tests that check the Mona interaction with users
