### ISSUE TITLE
Ordering food for meetup via Mona

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/mona#36]
Inspiration can be taken from the PR - https://github.com/datarockets/mona/pull/5
Repo with commits - https://github.com/chyrta/mona/commits/develop

Thanks @chyrta for inspiration!

**Comment by AleksSenkou** [comment]
We change the services of food ordering nearly once a year, supporting new services will be a huge challenge and probably won't be a supportable solution

Guess it can work if we order the same food all the time, but it's not 😄 

@yuliagaranok is there anything Mona can help you with during your Office management duties?

**Comment by yuliyaharanok** [comment]
@AleksSenkou I automated everything I could with the help of Slackbot. For now, I don't see anything else to automate in this process and don't have time to think about it more

**Comment by AleksSenkou** [comment]
Ok, closing 👍
