### ISSUE TITLE
Mona should not be active in non-domain slack channels like #dev

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/mona#49]
Example:

![image](https://user-images.githubusercontent.com/3635774/60447220-a35fc480-9c2b-11e9-9e08-86cfb9ef9225.png)

Link - https://datarockets.slack.com/archives/C50JWS3K5/p1561991571450300

**Comment by atatarenko** [comment]
@AleksSenkou we could remove Mona app from #dev channel if you wish.

**Comment by AleksSenkou** [comment]
@atatarenko yeah, it can help

Do you know why Mona was added to #dev channel?

**Comment by atatarenko** [comment]
@AleksSenkou not

**Comment by nikitasakau** [comment]
Am I right that it is not 'code' discussion. I mean we can remove Mona from channel if we don't want  to see her 🙂.

BTW, I see that Mona removed from #dev channel. So looks like this issue is resolved.

@AleksSenkou Can we close it?

**Comment by AleksSenkou** [comment]
@nikitasakov looks like we can close and reopen if have issues in the future

**Comment by AleksSenkou** [comment]
Thanks 😄
