### ISSUE TITLE
[Bug] Mona triggers when usual greeting words are included as parts of other words

### ISSUE THREAD

**Issue by andrei-sheina** [datarockets/mona#51]
![image](https://user-images.githubusercontent.com/11193254/66649972-271c4a80-ec38-11e9-8ad2-38545968f95d.png)

This is super annoying.

**Comment by AleksSenkou** [comment]
Duplicated, see - https://github.com/datarockets/mona/issues/20

@andrei-sheina please describe your case there so that this issue can be closed
