### ISSUE TITLE
When I develop the app I'd like to understand where I can find tokens for my bot for .env file

### ISSUE THREAD

**Issue by nikitasakau** [datarockets/mona#54]
For example it is not clear that `botToken` is a `Bot User OAuth Access Token` from slack.

**Comment by npupko** [comment]
@nikitasakov I can complete this issue and update `README.md` before I start making changes to the #24 (cos I just setting Mona up locally right now) and I can see which things are incomprehensible as a newcomer:)
What do u think?

**Comment by nikitasakau** [comment]
@npupko Sure, good idea 👍If you see issue without assignees, feel free to take it 🙂
